### ISSUE TITLE
Siri support

### ISSUE THREAD

**Issue by elahmo** [vaktija/vaktija.ba-ios#2]
Selam :)

Would it be possible to add support for Siri integration to the iOS application? This would enable some really useful options such as: 

- "When is the next prayer?" _(`prayer` is at `hh:mm`)_
- "How long until next prayer?" _(Next prayer is in `xx minutes`)_

Something like [this](https://itnext.io/siri-shortcut-tutorial-using-custom-intent-d0f836af5863) seems relatively simple to add.

I would try making the addition myself, however I do not have an Apple Developer account, and without it Siri capability cannot be added in XCode.

**Comment by vaktija** [comment]
Wa ʿalaykumu s-salam,

At the moment, regarding the app development, we are very limited. Anyway, it will be taken into consideration.

p.s.
Please contact us at info@vaktija.ba for hints about Apple Developer acc & Siri Xcode
